# emit_v2_json.R
# STAGED v2 emit (Phase 5). Produces data/latest_v2.json — a PARALLEL, NON-
# DESTRUCTIVE artifact that does NOT touch the live data/latest.json. The frontend
# cutover (reading latest_v2.json) is gated on James's approval.
#
# Two models, per James's 2026-06-10 decision (headline + toggle):
#   headline = qa_a05_q1_l01     (precision; MAI -> QA U-MIDAS, sel_alpha 0.05, q=1)
#   stress   = umidas_a20_q1_l01 (robustness/big-events; full U-MIDAS, alpha 0.20, q=1)
# Both on panel B3_nab_wmi (exclude AiG). Same MAI engine, different MIDAS step.
#
# Bias-aware CI level-bands from pipeline/seed/ci_params_v2*.json (regenerated by
# compute_ci_params.R off the v2 backtest). yoy = 4-quarter QoQ chain (3 actuals +
# nowcast). v1 comparison pointer read READ-ONLY from the live latest.json.
#
# Usage (from nowcasting_v2/, native Rscript + R_LIBS=pipeline lib):
#   Rscript R/emit_v2_json.R [--fetch]      (default reuses the cached vintage)

suppressWarnings(suppressMessages({
  here <- tryCatch(dirname(sys.frame(1)$ofile), error = function(e) NA)
}))
if (is.na(here) || !nzchar(here)) here <- "R"
source(file.path(here, "_setup.R"))
source(file.path(here, "build_panel.R"))
source(file.path(here, "transform_panel.R"))
source(file.path(here, "build_mai.R"))
source(file.path(here, "nowcast_midas.R"))
source(file.path(here, "run_nowcast_v2.R"))      # for get_prev_level() (guarded; no auto-run)
source(file.path(here, "..", "..", "pipeline", "ci_bands.R"))  # ci_level_band(), load_ci_params()
suppressMessages({ library(jsonlite) })

AIG <- c("aig_pmi", "aig_pci", "aig_psi")   # B3_nab_wmi panel excludes the AiG block

# yoy from the last 3 actual QoQ growths + the target-quarter nowcast.
.compute_yoy <- function(gdp, nowcast_qoq) {
  g <- gdp[order(as.Date(gdp$date)), ]
  last3 <- tail(g$value, 3L)                       # 3 most recent ACTUAL quarters
  chain <- prod(1 + c(last3, nowcast_qoq) / 100)   # + the nowcast = 4 quarters
  (chain - 1) * 100
}

emit_v2_json <- function(no_fetch = TRUE, repo_root = "..") {
  cat("=== emit_v2_json (staged, non-destructive) ===\n")

  # ---- shared inputs ----
  # ALWAYS rebuild the panel from data_raw/ (offline). Do NOT trust a stale
  # cache/panel_vintage_latest.rds: an earlier baseline cache silently dropped the
  # Westpac/extended-NAB survey block, which made exclude_ids=AIG a no-op and
  # produced B0-baseline numbers wearing B3 bands (Fable review B1, 2026-06-11).
  cat("[1] panel: build_panel() from data_raw/*.csv\n")
  wide <- build_panel()
  # Fail loud (project policy): the B3_nab_wmi model REQUIRES the survey block.
  if (!("wmi_sent" %in% names(wide)))
    stop("emit_v2_json: panel has no 'wmi_sent' column — survey block missing; refusing to nowcast the baseline panel under B3 bands.")
  nab_n <- sum(!is.na(wide[["nab_conf"]]))
  if (nab_n < 120L)
    stop(sprintf("emit_v2_json: nab_conf has only %d months — looks like the 39-month stub, not the extended B3 series.", nab_n))
  cat(sprintf("[1] panel OK: %d series; wmi_sent present, extended NAB (n=%d)\n",
              ncol(wide) - 1L, nab_n))
  tfs <- transform_panel(wide, "seed/panel_info.csv")
  gdp <- read.csv("data_raw/rt_dgdp_qtr.csv")
  # prev_level = realized level of the quarter BEFORE target (the $ anchor for the
  # bands). Prefer the published ACTUAL from latest.json (latest_actual); only fall
  # back to get_prev_level()'s ABS-fetch / v1-nowcast path if that's unavailable.
  pl <- tryCatch({
    j  <- jsonlite::fromJSON(file.path(repo_root, "data", "latest.json"))
    la <- j$latest_actual
    if (!is.null(la$gdp_chain_volume_millions))
      list(level = as.numeric(la$gdp_chain_volume_millions), date = la$quarter,
           source = "latest.json latest_actual (realized ABS)")
    else NULL
  }, error = function(e) NULL)
  if (is.null(pl)) pl <- get_prev_level(no_fetch = no_fetch, repo_root = repo_root)
  if (is.null(pl)) stop("emit_v2_json: could not resolve prev GDP level (need it for $ bands)")
  prev_level <- pl$level

  # ---- one model: build_mai(alpha) -> nowcast_midas(model) -> CI bands ----
  one_model <- function(id, name, sel_alpha, model, ci_path) {
    cat(sprintf("[model] %s : alpha=%.2f model=%s\n", id, sel_alpha, model))
    mai <- build_mai(tfs = tfs, sel_alpha = sel_alpha, dfm_q = 1L, exclude_ids = AIG,
                     out_csv = file.path("cache", paste0("mai_", id, ".csv")),
                     out_rds = file.path("cache", paste0("mai_", id, ".rds")))$mai
    nc  <- nowcast_midas(mai, gdp, prev_level = prev_level, model = model, qa_lag = 0L:1L)
    ci  <- load_ci_params(ci_path)
    qoq <- as.numeric(nc$qoq_growth)
    yoy <- .compute_yoy(gdp, qoq)
    b68 <- ci_level_band(qoq, prev_level, ci$qoq_bias_pp, ci$qoq_sd_pp, ci$z_68)
    b95 <- ci_level_band(qoq, prev_level, ci$qoq_bias_pp, ci$qoq_sd_pp, ci$z_95)
    list(
      model_id                  = id,
      model_name                = name,
      target_quarter            = nc$target_quarter,
      gdp_chain_volume_millions = round(as.numeric(nc$nowcast_level)),
      qoq_growth_pct            = round(qoq, 2),
      yoy_growth_pct            = round(yoy, 2),
      ci_68_low                 = b68$low,  ci_68_high = b68$high,
      ci_95_low                 = b95$low,  ci_95_high = b95$high,
      n_months_in_quarter       = nc$n_months_in_quarter,
      ci_basis                  = ci$basis,
      ci_n                      = ci$n,
      ci_sd_pp                  = ci$qoq_sd_pp,
      ci_bias_pp                = ci$qoq_bias_pp
    )
  }

  headline <- one_model("v2_qa_a05",   "MAI → QA U-MIDAS (precision)",
                        0.05, "qa",     "../pipeline/seed/ci_params_v2.json")
  stress   <- one_model("v2_umidas_a20", "MAI → full U-MIDAS (stress / big-events)",
                        0.20, "umidas", "../pipeline/seed/ci_params_v2_umidas.json")

  # ---- v1 comparison pointer (READ-ONLY from the live latest.json) ----
  v1 <- tryCatch({
    lj <- file.path(repo_root, "data", "latest.json")
    j  <- jsonlite::fromJSON(lj)
    list(model_name = "v1 (13-series DFM)",
         target_quarter = j$target_quarter,
         qoq_growth_pct = j$nowcast$qoq_growth_pct,
         yoy_growth_pct = j$nowcast$yoy_growth_pct,
         gdp_chain_volume_millions = j$nowcast$gdp_chain_volume_millions,
         source = "data/latest.json")
  }, error = function(e) { message("v1 pointer read failed: ", conditionMessage(e)); NULL })

  # data_through = latest MAI month (build_mai wrote it for the headline config).
  data_through <- tryCatch(
    format(max(as.Date(read.csv("cache/mai_v2_qa_a05.csv")[[1]]), na.rm = TRUE), "%Y-%m"),
    error = function(e) format(Sys.Date(), "%Y-%m"))

  out <- list(
    generated_at   = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"),
    schema         = "v2-staged-1",
    target_quarter = headline$target_quarter,
    data_through   = data_through,
    prev_level     = list(value = round(prev_level), date = as.character(pl$date), source = pl$source),
    models         = list(headline = headline, stress = stress),
    v1_comparison  = v1,
    note           = "STAGED v2 emit (parallel to live latest.json). Headline=precision; stress toggle=big-events. Pending James approval."
  )

  out_path <- file.path(repo_root, "data", "latest_v2.json")
  jsonlite::write_json(out, out_path, pretty = TRUE, auto_unbox = TRUE, na = "null")
  cat(sprintf("\nWROTE %s\n", normalizePath(out_path, mustWork = FALSE)))
  cat(sprintf("  headline %s : QoQ %+.2f%%  (68%% band $%s-%s m)\n",
              headline$target_quarter, headline$qoq_growth_pct, headline$ci_68_low, headline$ci_68_high))
  cat(sprintf("  stress           : QoQ %+.2f%%\n", stress$qoq_growth_pct))
  invisible(out)
}

if (sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  emit_v2_json(no_fetch = !("--fetch" %in% args))
}
