function param_vec = vec_parameter(param)
% VEC_PARAMETER  Turn parameters of nowcast model into vector.
%
%   PARAM_VEC = VEC_PARAMETER(PARAM) returns vector by vertically
%   concatenating individual parameters in PARAM:
%     PARAM is struct, see map_parameter.
%     PARAM_VEC is N_PARAMx1 array with
%     N_PARAM=1+N*(1+N_F+P_E+2)+N_F*(N_F*P_F+2)
%
%   Version: 2021 Dec 01 - Matlab R2020a

% Vectorize parameters
param_vec = [param.mu; ...
    param.gamma_g; ...
    param.Lambda(:); ...
    param.Phi(:); ...
    param.gamma_f; ...
    param.pi_f; ...
    param.phi(:); ...
    param.gamma_e; ...
    param.pi_e];

end